FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.19
#FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.19-arm64v8
#FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.19-arm32v7

# which version and flavour of the audiobot to use
ARG TS3_AUDIOBOT_RELEASE="develop"

#中国境内换源清华请去掉注释
#RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

# install all pre-requisites, these will be needed always
RUN apk add \
    opus-dev \
    ffmpeg

# download and install the TS3AudioBot in the specified version and flavour
RUN mkdir -p /app \
    && cd /app \
    && echo "downloading https://splamy.de/api/nightly/projects/ts3ab/${TS3_AUDIOBOT_RELEASE}/download -O TS3AudioBot.zip" \
    && wget https://splamy.de/api/nightly/projects/ts3ab/${TS3_AUDIOBOT_RELEASE}/download -O TS3AudioBot.zip \
    && unzip TS3AudioBot.zip \
    && rm TS3AudioBot.zip

# make data directory and chown it to the ts3bot user
RUN mkdir -p /app/data

# set the work dir to data, so users can properly mount their config files to this dir with -v /host/path/to/data:/data
WORKDIR /app/data

# expose the webserver port
EXPOSE 58913

CMD ["dotnet", "/app/TS3AudioBot.dll", "--non-interactive"]